ToolBoxDeveloper.TemplateEmail.MVC/Models/ErrorViewModel.cs
using System;

namespace ToolBoxDeveloper.TemplateEmail.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToolBoxDeveloper.TemplateEmail.MVC/Controllers/EmailConfigurationController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using ToolBoxDeveloper.TemplateEmail.Domain.Contracts.Services;
using ToolBoxDeveloper.TemplateEmail.Domain.Dto;

namespace ToolBoxDeveloper.TemplateEmail.MVC.Controllers
{
    public class EmailConfigurationController : Controller
    {
        private readonly IEmailConfigurationService _emailConfigurationService;
        public EmailConfigurationController(IEmailConfigurationService emailConfigurationService)
        {
            this._emailConfigurationService = emailConfigurationService;
        }
        // GET: EmailTemplateController
        public async Task<ActionResult> Index()
        {
            var list = await this._emailConfigurationService.GetConfigurations();

            return View(list);
        }


        // GET: EmailTemplateController/Create
        public ActionResult Create()
        {
            return View(new EmailConfigurationDto());
        }

        // POST: EmailTemplateController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(EmailConfigurationDto dto)
        {
            try
            {
                await this._emailConfigurationService.CreateOrUpdate(dto);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EmailTemplateController/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            var dto = await this._emailConfigurationService.GetById(id);

            return View(dto);
        }

        // POST: EmailTemplateController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EmailConfigurationDto dto)
        {
            try
            {
                await this._emailConfigurationService.CreateOrUpdate(dto);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EmailTemplateController/Delete/5
                
        public async Task<ActionResult> Delete(string id)
        {
            try
            {
                var dto = await this._emailConfigurationService.Delete(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ToolBoxDeveloper.TemplateEmail.MVC/Controllers/EmailTemplateController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using ToolBoxDeveloper.TemplateEmail.Domain.Contracts.Services;
using ToolBoxDeveloper.TemplateEmail.Domain.Dto;

namespace ToolBoxDeveloper.TemplateEmail.MVC.Controllers
{
    public class EmailTemplateController : Controller
    {
        private readonly IEmailTemplateService _emailTemplateService;
        public EmailTemplateController(IEmailTemplateService emailTemplateService)
        {
            this._emailTemplateService = emailTemplateService;
        }
        // GET: EmailTemplateController
        public async Task<ActionResult> Index()
        {
            var list = await this._emailTemplateService.GetTemplates();

            return View(list);
        }


        // GET: EmailTemplateController/Create
        public ActionResult Create()
        {
            return View(new EmailTemplateDto());
        }

        // POST: EmailTemplateController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async  Task<ActionResult> Create(EmailTemplateDto dto)
        {
            try
            {
                await this._emailTemplateService.CreateOrUpdate(dto);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EmailTemplateController/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            var dto = await this._emailTemplateService.GetById(id);

            return View(dto);
        }

        // POST: EmailTemplateController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EmailTemplateDto dto)
        {
            try
            {
                await this._emailTemplateService.CreateOrUpdate(dto);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EmailTemplateController/Delete/5

        public async Task<ActionResult> Delete(string id)
        {
            try
            {
                var dto = await this._emailTemplateService.Delete(id);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ToolBoxDeveloper.TemplateEmail.MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using ToolBoxDeveloper.TemplateEmail.MVC.Models;

namespace ToolBoxDeveloper.TemplateEmail.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ToolBoxDeveloper.TemplateEmail.MVC/Views/EmailConfiguration/Create.cshtml
@model ToolBoxDeveloper.TemplateEmail.Domain.Dto.EmailConfigurationDto
@{
    ViewData["Title"] = "Create";
}
<h1>Criar</h1>
<h4>Configurações</h4>
<hr />
<div class="jumbotron">
    <form asp-action="Create">
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-md-4">
                <label class="control-label">Host</label>
                <input asp-for="Host" class="form-control" />
                <span asp-validation-for="Host" class="text-danger"></span>
            </div>
            <div class="col-md-4">
                <label class="control-label">Porta</label>
                <input asp-for="Port" class="form-control" />
                <span asp-validation-for="Port" class="text-danger"></span>
            </div>
            <div class="col-md-4">
                <label class="control-label">Email</label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="col-md-4">
                <label class="control-label">Senha</label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <a asp-action="Index" class="btn btn-info btn-site">
                    <i class="fa fa-backward" aria-hidden="true"></i>
                    Voltar
                </a>
            </div>
            <div class="col-md-4">
                <button type="submit" class="btn btn-success btn-site">
                    <i class="fa fa-floppy-o" aria-hidden="true"></i>
                    Salvar
                </button>
            </div>
        </div>
    </form>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ToolBoxDeveloper.TemplateEmail.MVC/Views/EmailConfiguration/Edit.cshtml
@model ToolBoxDeveloper.TemplateEmail.Domain.Dto.EmailConfigurationDto
@{
    ViewData["Title"] = "Edit";
}
<h1>Editar</h1>
<h4>Configurações</h4>
<hr />
<div class="jumbotron">
    <form asp-action="Edit">
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(x => x.Id)
            <div class="col-md-4">
                <label class="control-label">Host</label>
                <input asp-for="Host" class="form-control" />
                <span asp-validation-for="Host" class="text-danger"></span>
            </div>
            <div class="col-md-4">
                <label class="control-label">Porta</label>
                <input asp-for="Port" class="form-control" />
                <span asp-validation-for="Port" class="text-danger"></span>
            </div>
            <div class="col-md-4">
                <label class="control-label">Email</label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="col-md-4">
                <label class="control-label">Senha</label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
        </div>
        <div class="row row-site">
            <div class="col-md-4">
                <a asp-action="Index" class="btn btn-info btn-site">
                    <i class="fa fa-backward" aria-hidden="true"></i>
                    Voltar
                </a>
            </div>
            <div class="col-md-4">
                <button type="submit" class="btn btn-success btn-site">
                    <i class="fa fa-floppy-o" aria-hidden="true"></i>
                    Salvar
                </button>
            </div>
        </div>
    </form>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ToolBoxDeveloper.TemplateEmail.MVC/Views/EmailConfiguration/Index.cshtml
@model IEnumerable<ToolBoxDeveloper.TemplateEmail.Domain.Dto.EmailConfigurationDto>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de Configurações</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">
        <i class="fa fa-plus" aria-hidden="true"></i>
        Novo
    </a>
</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Host</th>
            <th>Porta</th>
            <th>User</th>
            <th>Editar</th>
            <th>Deletar</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Host)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Port)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    <a href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-info">
                        <i class="fa fa-pencil" aria-hidden="true"></i>
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Delete", new { id = item.Id })" class="btn btn-danger">
                        <i class="fa fa-trash" aria-hidden="true"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

ToolBoxDeveloper.TemplateEmail.MVC/Views/EmailTemplate/Create.cshtml
@model ToolBoxDeveloper.TemplateEmail.Domain.Dto.EmailTemplateDto
@{
    ViewData["Title"] = "Create";
}
<h1>Criar</h1>
<h4>Templar</h4>
<hr />
<div class="row">
    <div class="col-md">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>
            <div class="form-group">
                <label class="control-label">Conteudo Body</label>
                @Html.TextAreaFor(x => x.Body, new { @class = "form-control summernote-site" })
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <a asp-action="Index" class="btn btn-info btn-site">
                        <i class="fa fa-backward" aria-hidden="true"></i>
                        Voltar
                    </a>
                </div>
                <div class="col-md-4">
                    <button type="submit" class="btn btn-success btn-site">
                        <i class="fa fa-floppy-o" aria-hidden="true"></i>
                        Salvar
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script type="text/javascript">
        $(document).ready(function () {
            $('.summernote-site').summernote();
        });
    </script>
}

ToolBoxDeveloper.TemplateEmail.MVC/Views/EmailTemplate/Edit.cshtml
@model ToolBoxDeveloper.TemplateEmail.Domain.Dto.EmailTemplateDto
@{
    ViewData["Title"] = "Edit";
}
<h1>Editar</h1>
<h4>Template</h4>
<hr />
<div class="row">
    <div class="col-md">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.HiddenFor(x => x.Id)
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>
            <div class="form-group">
                <label class="control-label">Conteudo Body</label>
                @Html.TextAreaFor(x => x.Body, new { @class = "form-control summernote-site" })
                @*<textarea asp-for="Body.ToString()" class="form-control summernote-site" />*@
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <a asp-action="Index" class="btn btn-info btn-site">
                        <i class="fa fa-backward" aria-hidden="true"></i>
                        Voltar
                    </a>
                </div>
                <div class="col-md-4">
                    <button type="submit" class="btn btn-success btn-site">
                        <i class="fa fa-floppy-o" aria-hidden="true"></i>
                        Salvar
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");

    }
    <script type="text/javascript">
        $(document).ready(function () {
            $('.summernote-site').summernote();
        });
    </script>
}

ToolBoxDeveloper.TemplateEmail.MVC/Views/EmailTemplate/Index.cshtml
@model IEnumerable<ToolBoxDeveloper.TemplateEmail.Domain.Dto.EmailTemplateDto>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de Templates</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">
        <i class="fa fa-plus" aria-hidden="true"></i>
        Novo
    </a>
</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Ativo</th>
            <th>Editar</th>
            <th>Excluir</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsActive)
                </td>
                <td>
                    <a href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-info">
                        <i class="fa fa-pencil" aria-hidden="true"></i>
                    </a>
                </td>
                <td>
                    <a href="@Url.Action("Delete", new { id = item.Id })" class="btn btn-danger">
                        <i class="fa fa-trash" aria-hidden="true"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

ToolBoxDeveloper.TemplateEmail.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ToolBoxDeveloper.TemplateEmail.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TemplateEmail</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/bootswatch/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/logo.png" class="logo-site"/>
                    @*Home*@
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EmailConfiguration" asp-action="Index">Configurações</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EmailTemplate" asp-action="Index">Templates</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ToolBoxDeveloper.TemplateEmail - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    @RenderSection("Scripts", required: false)
</body>
</html>